
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author enta
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    static ArrayList<Person> formandos = new ArrayList<>();
    int idperson = 1;

    static ArrayList<Curso> arraycurso = new ArrayList<>();
    int idarraycurso = 1;

    static ArrayList<Disciplina> arraydisciplina = new ArrayList<>();
    int idarraydisciplina = 1;

    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        horascurso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nomecurso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idcurso = new javax.swing.JTextField();
        guardarcursoBt = new javax.swing.JButton();
        restaurarcursoBt = new javax.swing.JButton();
        limparcursoBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        res = new javax.swing.JTextArea();
        modificarcurso = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        eliminarcurso = new javax.swing.JButton();
        selcurso = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        iddisciplina = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nomedisciplina = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        horasdisciplina = new javax.swing.JTextField();
        restaurarDisciplinaBt = new javax.swing.JButton();
        guardardisciplinaBt = new javax.swing.JButton();
        limparDisciplinaBt1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Cursos = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        Disciplinas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        modificardisciplina = new javax.swing.JButton();
        eliminardisciplina = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        seldisciplina = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        res1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        pais = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        altura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        limparBt = new javax.swing.JButton();
        guardarBt = new javax.swing.JButton();
        restaurarBt = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        idaluno = new javax.swing.JTextField();
        modificaraluno = new javax.swing.JButton();
        eliminaraluno = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        selaluno = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        res2 = new javax.swing.JTextArea();
        comboaluno = new javax.swing.JComboBox<>();
        combocurso = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Curso:");

        jLabel6.setText("Horas:");

        jLabel7.setText("IdCurso:");

        idcurso.setEditable(false);
        idcurso.setText("1");

        guardarcursoBt.setText("Guardar");
        guardarcursoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarcursoBtActionPerformed(evt);
            }
        });

        restaurarcursoBt.setText("Listar");
        restaurarcursoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarcursoBtActionPerformed(evt);
            }
        });

        limparcursoBt.setText("Limpar");
        limparcursoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparcursoBtActionPerformed(evt);
            }
        });

        res.setColumns(20);
        res.setRows(5);
        jScrollPane1.setViewportView(res);

        modificarcurso.setText("Modificar");
        modificarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarcursoActionPerformed(evt);
            }
        });

        jLabel14.setText("Selecionar ID do Curso:");

        eliminarcurso.setText("Eliminar");
        eliminarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcursoActionPerformed(evt);
            }
        });

        selcurso.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        selcurso.setMaximumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(guardarcursoBt))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(limparcursoBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modificarcurso))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eliminarcurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restaurarcursoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(horascurso))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomecurso))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idcurso)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(idcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(horascurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(guardarcursoBt)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(selcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limparcursoBt)
                            .addComponent(restaurarcursoBt))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modificarcurso)
                            .addComponent(eliminarcurso))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Curso", jPanel1);

        jLabel11.setText("IdDisciplinas:");

        iddisciplina.setEditable(false);
        iddisciplina.setText("1");

        jLabel9.setText("Disciplina:");

        jLabel10.setText("Horas:");

        restaurarDisciplinaBt.setText("Listar");
        restaurarDisciplinaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarDisciplinaBtActionPerformed(evt);
            }
        });

        guardardisciplinaBt.setText("Guardar");
        guardardisciplinaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardardisciplinaBtActionPerformed(evt);
            }
        });

        limparDisciplinaBt1.setText("Limpar");
        limparDisciplinaBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparDisciplinaBt1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Disciplinas");

        Cursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursosActionPerformed(evt);
            }
        });

        jLabel13.setText("Curso");

        Disciplinas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Associar disciplina a curso");

        modificardisciplina.setText("Modificar");
        modificardisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificardisciplinaActionPerformed(evt);
            }
        });

        eliminardisciplina.setText("Eliminar");
        eliminardisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminardisciplinaActionPerformed(evt);
            }
        });

        jLabel15.setText("Selecionar ID da Disciplina:");

        seldisciplina.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        res1.setColumns(20);
        res1.setRows(5);
        jScrollPane3.setViewportView(res1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomedisciplina)
                            .addComponent(horasdisciplina)
                            .addComponent(iddisciplina, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardardisciplinaBt)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(seldisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Disciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12)
                            .addComponent(Cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(modificardisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(22, 22, 22))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(limparDisciplinaBt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(34, 34, 34)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eliminardisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(restaurarDisciplinaBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iddisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomedisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(horasdisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardardisciplinaBt)
                    .addComponent(limparDisciplinaBt1)
                    .addComponent(restaurarDisciplinaBt))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificardisciplina)
                    .addComponent(eliminardisciplina)
                    .addComponent(jLabel15)
                    .addComponent(seldisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Disciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Disciplinas", jPanel2);

        jLabel4.setText("Altura:");

        altura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setText("Nome:");

        jLabel2.setText("Ano:");

        ano.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("País");

        limparBt.setText("Limpar");
        limparBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBtActionPerformed(evt);
            }
        });

        guardarBt.setText("Guardar");
        guardarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtActionPerformed(evt);
            }
        });

        restaurarBt.setText("Listar");
        restaurarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarBtActionPerformed(evt);
            }
        });

        jLabel8.setText("IdAluno:");

        idaluno.setEditable(false);
        idaluno.setText("1");

        modificaraluno.setText("Modificar");
        modificaraluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaralunoActionPerformed(evt);
            }
        });

        eliminaraluno.setText("Eliminar");
        eliminaraluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaralunoActionPerformed(evt);
            }
        });

        jLabel16.setText("Selecionar ID do Aluno:");

        selaluno.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        res2.setColumns(20);
        res2.setRows(5);
        jScrollPane4.setViewportView(res2);

        comboaluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combocurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setText("Aluno:");

        jLabel18.setText("Curso");

        jButton2.setText("Associar aluno a curso");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(pais))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idaluno))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(selaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(comboaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(combocurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(modificaraluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(limparBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(eliminaraluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(restaurarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(guardarBt)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBt)
                    .addComponent(limparBt)
                    .addComponent(restaurarBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(selaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificaraluno)
                    .addComponent(eliminaraluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combocurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Alunos", jPanel3);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void eliminaralunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaralunoActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Person.txt");
            if (formandos.size() == 0) {
                res2.append("Não existem formandos." + "\n");
            } else {
                int idFormando = (int) selaluno.getValue();
                if (idFormando <= 0 || idFormando > formandos.size()) {
                    res2.append("O formando " + idFormando + " não foi encontrado." + "\n");
                } else {
                    formandos.get(idFormando - 1);
                    formandos.remove(idFormando - 1);
                    res2.append("O formando " + idFormando + " foi eliminado." + "\n");
                }
            }
            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(formandos);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eliminaralunoActionPerformed

    private void modificaralunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaralunoActionPerformed
        // TODO add your handling code here:
        FileInputStream fileInputStream = null;
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Person.txt");
            if (formandos.size() == 0) {
                res2.append("Não existe alunos." + "\n");
            } else {
                int idaluno = (int) selaluno.getValue();
                if (idaluno <= 0 || idaluno > formandos.size()) {
                    res2.append("Nenhum Aluno selecionado" + "\n");
                } else {
                    formandos.get(idaluno - 1);
                    Person person = new Person();
                    person.setId(idaluno);
                    person.setPais(pais.getText());
                    person.setNome(nome.getText());
                    //    person.setAltura(Integer.parseInt(altura));

                    //  person.setAltura(altura.getText());
                    //  person.setAno(ano.getText());
                    formandos.set(idaluno - 1, person);
                    res2.append("Aluno com ID:" + idaluno + " foi alterado");

                }
            }
            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(arraydisciplina);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificaralunoActionPerformed

    private void restaurarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarBtActionPerformed
        FileInputStream fileInputStream = null;
        try {
            // TODO add your handling code here:
            fileInputStream = new FileInputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Person.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            formandos = (ArrayList<Person>) objectInputStream.readObject();
            objectInputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        res2.setText("");
        for (Person formandos : formandos) {
            res2.append(formandos.toString());
        }

        /*
        for (int x = 0; x < formandos.size(); x++) {
            res.append(String.valueOf("ID " + formandos.get(x).getId() + " Nome:" + nome.getName() + "\n");
            }

            idaluno.setText(String.valueOf(pessoa.getId()));
            pais.setText(pessoa.getPais());
            nome.setText(pessoa.getNome());
            ano.setText(String.valueOf(pessoa.getAno()));
            altura.setText(String.valueOf(pessoa.getAltura()));

            res2.setText("" + "\n");
            for (int x = 0; x < formandos.size(); x++) {
                res2.append("Id:" + String.valueOf(formandos.get(x).getId() + " Nome:" + pessoa.getNome()) + "\n");
            }

        }*/
    }//GEN-LAST:event_restaurarBtActionPerformed

    private void guardarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtActionPerformed
        try {
            Person person = new Person();
            // person.setId(Integer.parseInt(idaluno.getText()));
            person.setPais(pais.getText());
            person.setNome(nome.getText());
            person.setAno(Integer.parseInt(ano.getText()));
            person.setAltura(Integer.parseInt(altura.getText()));

            //dar id;
            person.setId(idperson++);
            idaluno.setText(String.valueOf(idperson));
            formandos.add(person);
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Person.txt");
            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(formandos);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarBtActionPerformed

    private void limparBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBtActionPerformed
        // TODO add your handling code here:
        pais.setText("");
        nome.setText("");
        ano.setText("");
        altura.setText("");
        res.setText("");
    }//GEN-LAST:event_limparBtActionPerformed

    private void eliminardisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminardisciplinaActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Disciplinaarray.txt");
            if (arraydisciplina.size() == 0) {
                res1.append("Não existem Disciplinas." + "\n");
            } else {
                int iddisciplina = (int) seldisciplina.getValue();
                if (iddisciplina <= 0 || iddisciplina > arraydisciplina.size()) {
                    res1.append("O Disciplinas " + iddisciplina + " não foi encontrado." + "\n");
                } else {
                    arraydisciplina.get(iddisciplina - 1);
                    arraydisciplina.remove(iddisciplina - 1);
                    res1.append("A Disciplina " + iddisciplina + " foi eliminada." + "\n");
                }
            }
            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(arraydisciplina);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eliminardisciplinaActionPerformed

    private void modificardisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificardisciplinaActionPerformed
        // TODO add your handling code here:
        FileInputStream fileInputStream = null;
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Disciplinaarray.txt");
            if (arraydisciplina.size() == 0) {
                res1.append("Não existem Disciplina." + "\n");
            } else {
                int iddisciplina = (int) seldisciplina.getValue();
                if (iddisciplina <= 0 || iddisciplina > arraydisciplina.size()) {
                    res1.append("Nenhuma Disciplina selecionada" + "\n");
                } else {

                    arraydisciplina.get(iddisciplina - 1);
                    Disciplina disciplina = new Disciplina();
                    disciplina.setIddisciplina(iddisciplina);
                    disciplina.setHorasdisciplina(Integer.parseInt(horasdisciplina.getText()));
                    disciplina.setNomedisciplina(nomedisciplina.getText());
                    arraydisciplina.set(iddisciplina - 1, disciplina);
                    res1.append("Disciplina com o ID:" + iddisciplina + " foi alterado ");

                }
            }
            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(arraydisciplina);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificardisciplinaActionPerformed

    private void CursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CursosActionPerformed

    private void limparDisciplinaBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparDisciplinaBt1ActionPerformed
        // TODO add your handling code here:
        nomedisciplina.setText("");
        horasdisciplina.setText("");
    }//GEN-LAST:event_limparDisciplinaBt1ActionPerformed

    private void guardardisciplinaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardardisciplinaBtActionPerformed
        // TODO add your handling code here:
        try {
            Disciplina disciplina = new Disciplina();
            //curso.setIdcurso(Integer.parseInt(idcurso.getText()));
            disciplina.setNomedisciplina(nomedisciplina.getText());
            disciplina.setHorasdisciplina(Integer.parseInt(horasdisciplina.getText()));

            //dar id;
            disciplina.setIddisciplina(idarraydisciplina++);
            iddisciplina.setText(String.valueOf(idarraydisciplina));
            arraydisciplina.add(disciplina);
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Disciplinaarray.txt");

            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(arraydisciplina);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardardisciplinaBtActionPerformed

    private void restaurarDisciplinaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarDisciplinaBtActionPerformed
        // TODO add your handling code here:
        FileInputStream fileInputStream = null;
        try {
            // TODO add your handling code here:
            fileInputStream = new FileInputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Disciplinaarray.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            arraydisciplina = (ArrayList<Disciplina>) objectInputStream.readObject();
            objectInputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        res1.setText("");
        for (Disciplina arraydisciplina : arraydisciplina) {
            res1.append(arraydisciplina.toString());
        }
    }//GEN-LAST:event_restaurarDisciplinaBtActionPerformed

    private void eliminarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcursoActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Cursoarray.txt");
            if (arraycurso.size() == 0) {
                res1.append("Não existem Cursos." + "\n");
            } else {
                int idcurso = (int) selcurso.getValue();
                if (idcurso <= 0 || idcurso > arraycurso.size()) {
                    res.append("O curso " + idcurso + " não foi encontrado." + "\n");
                } else {
                    arraycurso.get(idcurso - 1);
                    arraycurso.remove(idcurso - 1);
                    res.append("O Curso " + idcurso + " foi eliminado." + "\n");
                }
            }
            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(arraycurso);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eliminarcursoActionPerformed

    private void modificarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarcursoActionPerformed
        FileInputStream fileInputStream = null;
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Cursoarray.txt");
            if (arraycurso.size() == 0) {
                res.append("Não existem Cursos criados." + "\n");
            } else {
                int idCurso = (int) selcurso.getValue();
                if (idCurso <= 0 || idCurso > arraycurso.size()) {
                    res.append("Nenhum Curso selecionado" + "\n");
                } else {
                    arraycurso.get(idCurso - 1);
                    Curso curso = new Curso();
                    curso.setIdcurso(idCurso);
                    curso.setHoras(Integer.parseInt(horascurso.getText()));
                    curso.setNomecurso(nomecurso.getText());
                    arraycurso.set(idCurso - 1, curso);
                    res.append("O curso com o ID:" + idCurso + " foi alterado ");

                }
            }
            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(arraycurso);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificarcursoActionPerformed

    private void limparcursoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparcursoBtActionPerformed
        // TODO add your handling code here:

        horascurso.setText("");
        nomecurso.setText("");
    }//GEN-LAST:event_limparcursoBtActionPerformed

    private void restaurarcursoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarcursoBtActionPerformed
        // TODO add your handling code here:
        FileInputStream fileInputStream = null;
        try {
            // TODO add your handling code here:
            fileInputStream = new FileInputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Cursoarray.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            arraycurso = (ArrayList<Curso>) objectInputStream.readObject();
            objectInputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        res.setText("");
        for (Curso arraycurso : arraycurso) {
            res.append(arraycurso.toString());
        }
    }//GEN-LAST:event_restaurarcursoBtActionPerformed

    private void guardarcursoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarcursoBtActionPerformed
        // TODO add your handling code here:
        try {
            Curso curso = new Curso();
            //curso.setIdcurso(Integer.parseInt(idcurso.getText()));
            curso.setNomecurso(nomecurso.getText());
            curso.setHoras(Integer.parseInt(horascurso.getText()));

            //dar id;
            curso.setIdcurso(idarraycurso++);
            idcurso.setText(String.valueOf(idarraycurso));
            arraycurso.add(curso);
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\Users\\GRSI.LABINF1-PC07\\Desktop\\Proj\\Cursoarray.txt");

            try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(arraycurso);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(App.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarcursoBtActionPerformed

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cursos;
    private javax.swing.JComboBox<String> Disciplinas;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTextField altura;
    private javax.swing.JTextField ano;
    private javax.swing.JComboBox<String> comboaluno;
    private javax.swing.JComboBox<String> combocurso;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JButton eliminaraluno;
    private javax.swing.JButton eliminarcurso;
    private javax.swing.JButton eliminardisciplina;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton guardarBt;
    private javax.swing.JButton guardarcursoBt;
    private javax.swing.JButton guardardisciplinaBt;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextField horascurso;
    private javax.swing.JTextField horasdisciplina;
    private javax.swing.JTextField idaluno;
    private javax.swing.JTextField idcurso;
    private javax.swing.JTextField iddisciplina;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton limparBt;
    private javax.swing.JButton limparDisciplinaBt1;
    private javax.swing.JButton limparcursoBt;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton modificaraluno;
    private javax.swing.JButton modificarcurso;
    private javax.swing.JButton modificardisciplina;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomecurso;
    private javax.swing.JTextField nomedisciplina;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JTextField pais;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JTextArea res;
    private javax.swing.JTextArea res1;
    private javax.swing.JTextArea res2;
    private javax.swing.JButton restaurarBt;
    private javax.swing.JButton restaurarDisciplinaBt;
    private javax.swing.JButton restaurarcursoBt;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JSpinner selaluno;
    private javax.swing.JSpinner selcurso;
    private javax.swing.JSpinner seldisciplina;
    // End of variables declaration//GEN-END:variables

}
